LOCAL_PATH := $(call my-dir)

# include $(CLEAR_VARS)
# LOCAL_MODULE := loader_util
# LOCAL_C_INCLUDES := $(LOCAL_PATH)/include
# LOCAL_SRC_FILES := util.c
# include $(BUILD_SHARED_LIBRARY)

# include $(CLEAR_VARS)
# LOCAL_MODULE := loader
# LOCAL_C_INCLUDES := $(LOCAL_PATH)/include
# LOCAL_SRC_FILES := loader.c
# LOCAL_SHARED_LIBRARIES := loader_util
# include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := loader
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include
$(info guobin LOADER_SRC_FILES=$(LOADER_SRC_FILES))
LOCAL_SRC_FILES := $(LOADER_SRC_FILES)
LOCAL_CFLAGS := $(CFLAGS)
LOCAL_LDFLAGS := $(LDFLAGS)
LOCAL_ASFLAGS := $(ASFLAGS)
include $(BUILD_EXECUTABLE)
